# style
set-option -g status-style bg=#181616

set-option -g status-left '#[bg=#0d0c0c] #S #[bg=#181616,fg=#0d0c0c]'
set-option -g status-left-length 50

set-option -g status-right '#[fg=#0d0c0c]#[bg=#0d0c0c,fg=#c5c9c5]  #(whoami) #[fg=#181616]#[bg=#181616,fg=#c5c9c5] 󰍹 #H '

set-option -g window-status-style bg=#181616
set-option -g window-status-separator "#[fg=#c5c9c5]"
set-option -g window-status-format '#[fg=#c5c9c5] #{window_index} #{window_name} '
set-option -g window-status-current-format '#[fg=#76946A] #{window_index} #{window_name} '

set-option -g renumber-windows on

set -g message-style 'fg=#76946A'

set-window-option -g mode-style 'bg=#181616 fg=#76946A'
