directories:
  - path: ~/Programming/
    sub_directories:
      - path: AppArmor
      - path: neovim-plugins
      - path: TUWien
        sub_directories:
          - path: Uebersetzerbau
  - path: ~/.config
    exclude:
      - Nextcloud
      - GIMP
      - Thunar
      - xfce4
      - dconf
  - path: ~/Syncthing/Notes/TUWien/WS24
  - path: ~/Syncthing/Notes/TUWien/SS25
  - path: ~/Syncthing/Notes
    only_self: true
  - path: ~/.dotfiles
    only_self: true
  - path: ~/.ansible
    only_self: true
