#!/usr/bin/env bash

~/.config/sxhkd/launch.sh

autorandr --load default

MONITOR_COUNT=$(xrandr --query | grep " connected " | awk '{ print$1 }' | wc -l)
PRIMARY_MONITOR=$(xrandr --query | grep " connected primary" | cut -d" " -f1)
OTHER_MONITORS=($(xrandr --query | grep " connected " | grep -v " connected primary " | cut -d" " -f1))

if [ $MONITOR_COUNT -eq 1 ]; then
    bspc monitor -d code system browser chat music vm
    bspc monitor
else
    bspc monitor $PRIMARY_MONITOR -d code system
    bspc monitor ${OTHER_MONITORS[0]} -d browser chat music vm
fi

bspc wm --reorder-monitors $PRIMARY_MONITOR ${OTHER_MONITORS[@]}

bspc config border_width         2
bspc config window_gap          10

bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"
bspc config active_border_color "#6e6a86"
bspc config presel_feedback_color "#6e6a86"

bspc config pointer_follows_monitor true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a kitty-dev desktop='^1'
bspc rule -a firefox desktop='^3'
bspc rule -a Firefox desktop='^3'
bspc rule -a discord desktop='^4'
bspc rule -a spotify desktop='^5'
bspc rule -a Emacs state=tiled

~/.config/bspwm/autostart.sh
