#!/usr/bin/sh

sxhkd &

bspc monitor DP-4 -d code system
bspc monitor HDMI-0 -d browser chat music vm

bspc wm --reorder-monitors DP-4 HDMI-0

bspc config border_width         2
bspc config window_gap          10

bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"
bspc config active_border_color "#6e6a86"
bspc config presel_feedback_color "#6e6a86"

bspc config pointer_follows_monitor true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^3'
bspc rule -a discord desktop='^4'
bspc rule -a spotify desktop='^5'

~/.config/bspwm/autostart.sh
