#!/usr/bin/sh

sxhkd &

bspc monitor DP-4 -d code system
bspc monitor HDMI-0 -d browser chat music

bspc wm --reorder-monitors DP-4 HDMI-0

bspc config border_width         2
bspc config window_gap          10

bspc config normal_border_color "#161A1D"
bspc config active_border_color "#161A1D"
bspc config focused_border_color "#E5383B"
bspc config presel_feedback_color "#660708"

bspc config pointer_follows_monitor true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^3'
bspc rule -a discord desktop='^4'
bspc rule -a spotify desktop='^5'

~/.config/bspwm/autostart.sh
